version: '3.7'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment: 
      - API_PORT=${API_PORT}
      - DB_URL=${DB_URL}
    depends_on: 
      - mongo
    networks:
      - mongo
  mongo: 
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - mongo
    restart: always
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
networks:
  mongo:
    name: mongo